package main

import (
	//_ "megaCrawler/plugins/aiaa"
	//_ "megaCrawler/plugins/ait" // 反爬？
	//_ "megaCrawler/plugins/apnorc"
	//_ "megaCrawler/plugins/brennancenter"
	//_ "megaCrawler/plugins/chathamhouse"
	//_ "megaCrawler/plugins/cprindia"
	//_ "megaCrawler/plugins/csis"
	//_ "megaCrawler/plugins/demos"
	//_ "megaCrawler/plugins/heritage"
	//_ "megaCrawler/plugins/ids"
	//_ "megaCrawler/plugins/ipcs"
	//_ "megaCrawler/plugins/ips"
	//_ "megaCrawler/plugins/kiep"
	//_ "megaCrawler/plugins/maritimeindia"
	//_ "megaCrawler/plugins/piie"
	//_ "megaCrawler/plugins/prri"
	//_ "megaCrawler/plugins/quincyinst"
	//_ "megaCrawler/plugins/rockefeller"
	//_ "megaCrawler/plugins/rra"
	//_ "megaCrawler/plugins/rusi"
	//_ "megaCrawler/plugins/si"
	//_ "megaCrawler/plugins/siia"
	//_ "megaCrawler/plugins/southasiajournal"
	//_ "megaCrawler/plugins/splcenter"
	//_ "megaCrawler/plugins/spri"
	//_ "megaCrawler/plugins/stanford"
	//_ "megaCrawler/plugins/vifindia"
	//_ "megaCrawler/plugins/kdi"
	//_ "megaCrawler/plugins/asaninst"
	//_ "megaCrawler/plugins/lowyinstitute"
	_ "megaCrawler/plugins/swp_berlin"
)
